version: 1

services:
  - type: web
    name: sst-dashboard-cabicho
    env: python
    plan: free
    region: ohio
    branch: sst-dashboard
    rootDir: sst-dashboard-render
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard_sst.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: true
      - key: GRADIO_SERVER_PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: sst-api-cabicho
    env: python
    plan: free
    region: ohio
    branch: sst-dashboard
    rootDir: sst-dashboard-render/api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true
