# render.yaml
services:
  - type: web
    name: multiclass-gradio-dashboard
    env: docker
    plan: free
    dockerfile: Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GRADIO_SERVER_NAME
        value: 0.0.0.0
      - key: GRADIO_SERVER_PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true