# render.yaml
services:
  - type: web
    name: rossmann-dashboard
    env: python
    plan: free
    buildCommand: |
      # Buscar e entrar no diretório do projeto
      if [ -f "portfolio_projectos/rossmann-dashboard/requirements.txt" ]; then
        cd portfolio_projectos/rossmann-dashboard
      elif [ -f "rossmann-dashboard/requirements.txt" ]; then
        cd rossmann-dashboard
      elif [ -f "requirements.txt" ]; then
        echo "✅ Usando diretório atual"
      else
        echo "🔍 Procurando requirements.txt..."
        PROJECT_DIR=$(find . -name "requirements.txt" -exec dirname {} \; | head -1)
        if [ -n "$PROJECT_DIR" ]; then
          cd "$PROJECT_DIR"
          echo "✅ Entrando em: $(pwd)"
        else
          echo "❌ requirements.txt não encontrado!"
          exit 1
        fi
      fi
      pip install -r requirements.txt
    startCommand: |
      # Mesma lógica para start
      if [ -f "portfolio_projectos/rossmann-dashboard/app.py" ]; then
        cd portfolio_projectos/rossmann-dashboard
      elif [ -f "rossmann-dashboard/app.py" ]; then
        cd rossmann-dashboard
      elif [ -f "app.py" ]; then
        echo "✅ Usando diretório atual"
      else
        echo "🔍 Procurando app.py..."
        PROJECT_DIR=$(find . -name "app.py" -exec dirname {} \; | head -1)
        if [ -n "$PROJECT_DIR" ]; then
          cd "$PROJECT_DIR"
          echo "✅ Entrando em: $(pwd)"
        else
          echo "❌ app.py não encontrado!"
          exit 1
        fi
      fi
      gunicorn app:server --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DASH_DEBUG_MODE
        value: false
      - key: PORT
        value: 8050
    healthCheckPath: /_dash-health-check