# render.yaml (na raiz do repositório)
services:
  - type: web
    name: multiclass-gradio-dashboard
    env: python
    plan: free

    #rootDir: portfolio_projectos/portfolio_multiclasse
    # Comandos que entram na subpasta do projeto
    buildCommand: |
      cd portfolio_multiclasse
      pip install -r requirements.txt
    startCommand: |
      cd portfolio_multiclasse
      python app_gradio.py

    envVars:
      - key: GRADIO_SERVER_NAME
        value: 0.0.0.0
      - key: GRADIO_SERVER_PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true

  #- type: web
  #  name: outro-projeto
  #  env: python
  #  plan: free
  #  rootDir: projetos/outro_projeto
  #  buildCommand: pip install -r requirements.txt
  #  startCommand: python app.py
  #  envVars:
  #    - key: PYTHON_VERSION
  #      value: 3.9.0