# render.yaml (na raiz do repositório)
services:
  - type: web
    name: multiclass-gradio-dashboard
    env: docker
    dockerfile: Dockerfile
    plan: free
    rootDir: portfolio_projectos/portfolio_multiclasse
    autoDeploy: true