services:
  - type: web
    name: multiclass-gradio-dashboard
    env: docker
    dockerfile: Dockerfile
    envVars:
      - key: GRADIO_SERVER_PORT
        value: "10000"
    plans:
      - name: starter
    numInstances: 1