version: '3.3'

services:
  multiclass-gradio:
    build:
      context: .
      dockerfile: Dockerfile-gradio
    container_name: multiclass-gradio-dashboard
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      - ./data:/app/data:ro
      - ./assets:/app/assets:ro
      - ./src:/app/src:ro
    restart: unless-stopped

#networks:
#  default:
#    driver: bridge